DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Guilds;
DROP TABLE IF EXISTS SteamBindings;
DROP TABLE IF EXISTS IsleServers;
DROP TABLE IF EXISTS IsleStore;
DROP TABLE IF EXISTS TeleportLocations;
DROP TABLE IF EXISTS PoiLocations;
DROP TABLE IF EXISTS Dinos;